title: One Percent Better
email: lucas.cucolo@gmail.com
description: >-
  Writing about personal development, continuous improvement, and learning English.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lucascucolo.github.io" # the base hostname & protocol for your sites
theme: minima